import type { Attempt, Dispute, JudgeTest, LedgerEvent, Mandate, Payment } from './types';

export const PRINCIPAL = 'Marta Silva';

export const mandates: Mandate[] = [
  {
    id: 'mandate_demo_01',
    principal: 'Marta Silva',
    agent: 'Travel Assistant',
    status: 'ACTIVE',
    perTransaction: 200,
    monthlyLimit: 600,
    committed: 130,
    reserved: 0,
    uses: 3,
    maxUses: 5,
    category: 'Travel',
    destinations: ['Brazil', 'Argentina', 'Chile'],
    currency: 'USD',
    maxLiveReservations: 1,
    liveReservations: 0,
    lastActivity: '2 min ago',
    createdAt: '2026-08-29 17:58:04',
    expiresAt: '2026-09-29 17:58:04',
    revocation: {
      liveCheck: true,
      lastCheckedSeconds: 0.4,
      revocationId: 'rev_01JAV7QK2M',
      registry: 'aval.local/.well-known/aval-revocation',
      epoch: 0,
    },
    timeline: [
      { label: 'Mandate created', at: '17:58:04', done: true, tone: 'neutral' },
      { label: 'Signed', at: '17:58:06', done: true, tone: 'neutral' },
      { label: 'Authorization used', at: '18:05:12', done: true, tone: 'allow' },
      { label: 'Revoked', at: '—', done: false, tone: 'deny' },
    ],
  },
  {
    id: 'mandate_demo_02',
    principal: 'João Martins',
    agent: 'Shopping Agent',
    status: 'ACTIVE',
    perTransaction: 150,
    monthlyLimit: 900,
    committed: 410,
    reserved: 0,
    uses: 6,
    maxUses: 12,
    category: 'Retail',
    destinations: ['Brazil'],
    currency: 'USD',
    maxLiveReservations: 2,
    liveReservations: 0,
    lastActivity: '41 min ago',
    createdAt: '2026-08-21 09:12:41',
    expiresAt: '2026-09-21 09:12:41',
    revocation: {
      liveCheck: true,
      lastCheckedSeconds: 0.6,
      revocationId: 'rev_01JAV5T0XB',
      registry: 'aval.local/.well-known/aval-revocation',
      epoch: 0,
    },
    timeline: [
      { label: 'Mandate created', at: '09:12:41', done: true, tone: 'neutral' },
      { label: 'Signed', at: '09:12:44', done: true, tone: 'neutral' },
      { label: 'Authorization used', at: '17:24:09', done: true, tone: 'allow' },
      { label: 'Revoked', at: '—', done: false, tone: 'deny' },
    ],
  },
  {
    id: 'mandate_demo_03',
    principal: 'Ana Costa',
    agent: 'Travel Assistant',
    status: 'REVOKED',
    perTransaction: 250,
    monthlyLimit: 750,
    committed: 250,
    reserved: 0,
    uses: 1,
    maxUses: 4,
    category: 'Travel',
    destinations: ['Portugal', 'Spain'],
    currency: 'USD',
    maxLiveReservations: 1,
    liveReservations: 0,
    lastActivity: '3 h ago',
    createdAt: '2026-08-18 14:02:10',
    expiresAt: '2026-09-18 14:02:10',
    revocation: {
      liveCheck: true,
      lastCheckedSeconds: 0.5,
      revocationId: 'rev_01JAV2C9PL',
      registry: 'aval.local/.well-known/aval-revocation',
      epoch: 1,
    },
    timeline: [
      { label: 'Mandate created', at: '14:02:10', done: true, tone: 'neutral' },
      { label: 'Signed', at: '14:02:13', done: true, tone: 'neutral' },
      { label: 'Authorization used', at: '15:31:55', done: true, tone: 'allow' },
      { label: 'Revoked', at: '16:44:02', done: true, tone: 'deny' },
    ],
  },
  {
    id: 'mandate_demo_04',
    principal: 'Lucas Prado',
    agent: 'Travel Assistant',
    status: 'ACTIVE',
    perTransaction: 120,
    monthlyLimit: 480,
    committed: 118.5,
    reserved: 0,
    uses: 2,
    maxUses: 8,
    category: 'Travel',
    destinations: ['Brazil', 'Uruguay'],
    currency: 'USD',
    maxLiveReservations: 1,
    liveReservations: 0,
    lastActivity: '18 min ago',
    createdAt: '2026-08-26 11:40:00',
    expiresAt: '2026-09-26 11:40:00',
    revocation: {
      liveCheck: true,
      lastCheckedSeconds: 0.5,
      revocationId: 'rev_01JAV8W3ND',
      registry: 'aval.local/.well-known/aval-revocation',
      epoch: 0,
    },
    timeline: [
      { label: 'Mandate created', at: '11:40:00', done: true, tone: 'neutral' },
      { label: 'Signed', at: '11:40:03', done: true, tone: 'neutral' },
      { label: 'Authorization used', at: '17:46:21', done: true, tone: 'allow' },
      { label: 'Revoked', at: '—', done: false, tone: 'deny' },
    ],
  },
];

export const attempts: Attempt[] = [
  {
    id: 'att_001',
    mandateId: 'mandate_demo_01',
    agent: 'Travel Assistant',
    merchant: 'VuelaYa',
    item: 'Flight',
    route: 'São Paulo → Buenos Aires',
    amount: 130,
    currency: 'USD',
    decision: 'ALLOW',
    reason: 'WITHIN_TRANSACTION_LIMIT',
    paymentId: 'pay_001',
    captured: true,
    decisionHandle: 'dh_8b31af02',
    termsHash: 'sha256:4f1c9ae7d2b0',
    expiresIn: 118,
  },
  {
    id: 'att_002',
    mandateId: 'mandate_demo_01',
    agent: 'Travel Assistant',
    merchant: 'HotelNow',
    item: 'Hotel',
    route: 'Buenos Aires · 3 nights',
    amount: 300,
    currency: 'USD',
    decision: 'ESCALATE',
    reason: 'EXCEEDS_TRANSACTION_LIMIT',
    paymentId: 'pay_002',
    decisionHandle: 'dh_1d77bc44',
    termsHash: 'sha256:9a02ff31c7e5',
    expiresIn: 118,
  },
  {
    id: 'att_003',
    mandateId: 'mandate_demo_01',
    agent: 'Shopping Agent',
    merchant: 'TechStore',
    item: 'Business class flight',
    amount: 900,
    currency: 'USD',
    decision: 'DENY',
    reason: 'MANDATE_CEILING_EXCEEDED',
    paymentId: 'pay_003',
    decisionHandle: 'dh_c0e9124a',
    termsHash: 'sha256:71bd40e8aa19',
    expiresIn: 0,
  },
  {
    id: 'att_004',
    mandateId: 'mandate_demo_01',
    agent: 'Travel Assistant',
    merchant: 'FlightHub',
    item: 'Flight',
    route: 'Buenos Aires → Santiago',
    amount: 220,
    currency: 'USD',
    decision: 'ESCALATE',
    reason: 'EXCEEDS_TRANSACTION_LIMIT',
    paymentId: 'pay_004',
    decisionHandle: 'dh_5e2200fd',
    termsHash: 'sha256:22ce8bb14d07',
    expiresIn: 96,
  },
];

export const payments: Payment[] = [
  { id: 'pay_001', attemptId: 'att_001', agent: 'Travel Assistant', merchant: 'VuelaYa', amount: 130, currency: 'USD', status: 'SETTLED' },
  { id: 'pay_002', attemptId: 'att_002', agent: 'Travel Assistant', merchant: 'HotelNow', amount: 300, currency: 'USD', status: 'ESCALATED' },
  { id: 'pay_003', attemptId: 'att_003', agent: 'Shopping Agent', merchant: 'TechStore', amount: 900, currency: 'USD', status: 'DECLINED' },
  { id: 'pay_004', attemptId: 'att_004', agent: 'Travel Assistant', merchant: 'FlightHub', amount: 220, currency: 'USD', status: 'IN_DOUBT', note: 'Awaiting reconciliation with the processor.' },
  // Settled earlier today on the other mandates. They keep "authorized today" a
  // real sum of this table rather than a number typed into a card.
  { id: 'pay_005', agent: 'Travel Assistant', merchant: 'RodoSul', amount: 118.5, currency: 'USD', status: 'SETTLED' },
  { id: 'pay_006', agent: 'Shopping Agent', merchant: 'LivrariaBR', amount: 180, currency: 'USD', status: 'SETTLED' },
];

export const ledger: LedgerEvent[] = [
  { id: 'ev_01', time: '18:04:32', type: 'MANDATE_CREATED', actor: 'Marta Silva', txId: 'mandate_demo_01', hash: 'a17f04c9', status: 'OK' },
  { id: 'ev_02', time: '18:05:10', type: 'OFFER_ISSUED', actor: 'VuelaYa', txId: 'off_9e21', hash: 'b83d7710', status: 'OK' },
  { id: 'ev_03', time: '18:05:12', type: 'AUTHORIZATION_ALLOWED', actor: 'AVAL Gate', txId: 'dh_8b31af02', hash: 'c0192ae4', status: 'OK' },
  { id: 'ev_04', time: '18:05:13', type: 'CAPTURE_COMMITTED', actor: 'AVAL Core', txId: 'res_44b1', hash: 'd52ba09f', status: 'OK' },
  { id: 'ev_05', time: '18:05:14', type: 'PAYMENT_SUBMITTED', actor: 'PSP', txId: 'pay_001', hash: 'e7c31b28', status: 'OK' },
  { id: 'ev_06', time: '18:05:16', type: 'PAYMENT_SETTLED', actor: 'PSP', txId: 'pay_001', hash: 'f10d6ec3', status: 'OK' },
  { id: 'ev_07', time: '18:07:02', type: 'AUTHORIZATION_ESCALATED', actor: 'AVAL Gate', txId: 'dh_1d77bc44', hash: '2b4419ad', status: 'HELD' },
  { id: 'ev_08', time: '18:09:41', type: 'AUTHORIZATION_DENIED', actor: 'AVAL Gate', txId: 'dh_c0e9124a', hash: '3f88cc10', status: 'REJECTED' },
];

export const disputes: Dispute[] = [
  {
    id: 'dsp_001',
    paymentId: 'pay_001',
    merchant: 'VuelaYa',
    amount: 130,
    claim: 'Cardholder states the flight was never authorized by a human.',
    verdict: 'REJECTED',
    evidence: [
      'Mandate mandate_demo_01 signed by the principal at 17:58:06',
      'Offer signature from VuelaYa verified at 18:05:10',
      'Authorization dh_8b31af02 issued inside the allow band',
      'Capture committed under a single mandate lock at 18:05:13',
      'Settlement receipt hash f10d6ec3 matches the terms hash',
    ],
    openedAt: '2026-08-29 19:12:00',
  },
  {
    id: 'dsp_002',
    paymentId: 'pay_003',
    merchant: 'TechStore',
    amount: 900,
    claim: 'Merchant claims the agent held a valid authorization for the charge.',
    verdict: 'UPHELD',
    evidence: [
      'No AUTHORIZATION_ALLOWED event exists for dh_c0e9124a',
      'Ledger records AUTHORIZATION_DENIED with MANDATE_CEILING_EXCEEDED',
      'No reservation was ever committed against the mandate',
    ],
    openedAt: '2026-08-29 19:40:00',
  },
];

export const judgeTests: JudgeTest[] = [
  { id: 'jt_psp_offline', name: 'PSP offline', description: 'Cut the processor mid-capture.', expected: 'IN_DOUBT', tone: 'hold', state: 'idle' },
  { id: 'jt_psp_decline', name: 'PSP decline', description: 'Processor refuses a committed capture.', expected: 'DECLINED + COMPENSATED', tone: 'deny', state: 'idle' },
  { id: 'jt_fake_webhook', name: 'Fake settlement webhook', description: 'Forge a settlement callback.', expected: 'WEBHOOK_SIGNATURE_INVALID', tone: 'verify', state: 'idle' },
  { id: 'jt_dup_webhook', name: 'Duplicate webhook', description: 'Replay a genuine settlement callback.', expected: 'WEBHOOK_REPLAY', tone: 'verify', state: 'idle' },
  { id: 'jt_griefing', name: 'Reservation griefing', description: 'Hold the budget with parallel reservations.', expected: 'RESERVATION_LIMIT', tone: 'deny', state: 'idle' },
  { id: 'jt_replay', name: 'Request replay', description: 'Resend a spent authorization nonce.', expected: 'REQUEST_NONCE_REPLAY', tone: 'verify', state: 'idle' },
  { id: 'jt_panic', name: 'Panic capsule', description: 'Revoke mid-flight and buy again.', expected: 'MANDATE_REVOKED', tone: 'deny', state: 'idle' },
  { id: 'jt_clock', name: 'Production clock bypass', description: 'Move the clock to expire a mandate.', expected: '404 DEMO_ENDPOINT_NOT_AVAILABLE', tone: 'verify', state: 'idle' },
];
